ML/MachineLearning.md, README.md
=> Resources Added for ML

Blockchain/blockchain.md
Blockchain resources added with documentation of basic blockchain components and frameworks
=> blockchain added

Backend/DJANGO.md
A comprehensive approach would be great to follow, which covers most of the topics in django, hands-on-practically.
=> Added a full course link to DJANGO.md (The readme file of Django)

CC_and_DSA/DSA.md
Also sorted all of them by increasing difficulty
=> Added more data structures and algorithms

ML/MACHINE_LEARNING.md
Added resources for AdaBoost and XGBoost.
=> Adding resources for AdaBoost and XGBoost(ML) under issue number 15 for Hacktoberfest

CloudComputing/DIGITALOCEAN.md, README.md
Tried my best to talk about DigitalOcean in a short and simple way. 😀
=> Added DigitalOcean Docs, fixes #22

DBMS/DBMS.md
Added Image, structured content in table format according to the issue raised.
=> Updated README for DBMS 

Design/UI-UX.md
Adds additional resources to Design > UI/UX
=> add additional UI/UX resources

CC_and_DSA/DSA.md, Frontend/WEB.md
=> added link for cp algorithms in dsa.md 

Backend/DENO.md
I added a new resource website to improve learning more.
=> Added New Resource website

Design/UI-UX.md, README.md, Security/SECURITY.md, Security/WEBSITE_SECURITY.md
Added Resources for:
- Security
- Design (UI/UX)
@N0v0cain3 pls merge
=> Added Resources

AugmentedReality/Vuforia.md
=> Added Vuforia.md

AugmentedReality/SparkAR.md
=> Added SparkAR

AugmentedReality/LensStudio.md
=> Added Lens Studio

AugmentedReality/ARKit.md
=> Added ARKit

DevOps/DOCKER.md, Security/WEBSITE_SECURITY.md
- Added Docker Compose
- Added SQL Injection Cheat Sheets for handy access
@N0v0cain3 kindly merge.
=> Added Resources In Security and DevOps

ML/DEEP_LEARNING.md, ML/MACHINE_LEARNING.md
Added Tensorflow.js, Github Copilot, Naive Bayes resources
@VisheshBansal
=> Added resouces in ML and DL

Blockchain/BLOCKCHAIN.md
Make two new section one for blockchain core concept and one for books. In both section I added one of the best resources. Also added one resource in Solidity and Ethereum both section.
=> Make-new-section-Added-Resources

README.md, Web-Performance/WEB-PERFORMANCE-OPTIMISATION.md
'Website Performance Optimisation' Folder Added
Things Added:
-Why WPO
-Tips to improve website performance
-Courses available
-Blog Links Added
Readme and Index updated and linked to WPO folder
@NeelGhoshal
=> Added a New Folder WPO

OperatingSystems/OPERATING-SYSTEMS.md
I think this is a typo because the readme is about systems programming.
=> Digital Marketing?

Backend/GRAPHQL.md
=> Fixed redundant anchor tag

README.md, Wordpress/Blogs.md, Wordpress/Books.md, Wordpress/Courses.md
List of WordPress Resources including books, blogs and courses which are absolutely free.
=> Wordpress Resources Added

Frontend/REACT.md
Added tutorial link in both Hindi and English
=> Added Tutorials

Blockchain/BLOCKCHAIN.md
Hello.
I have included some blockchain resources that helped me get started in the space. I hope it is to your standard.
It's a great curated format of resources this is. I am checking out the other categories. I will try to contribute some more in other domains as well. I am fascinated with such lists, as they make live as a developer easier. 
Thanks.
=> Include Blockchain resources
